plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
remote_theme: jeroenvanwissen/pastel-jekyll-theme

style_light: mocha
style_dark: mocha

title: Jeroen van Wissen
description:
url: https://jeroenvanwissen.github.io
timezone: Europe/Amsterdam
future: true
